---
image:
  file: .gitpod.Dockerfile
tasks:
  - init: |
      npm install
      cd subgraphs/creatify && yarn install && cd ../..
      cd subgraphs/marketplace && yarn install && cd ../..
  - name: Smart contract
    command: |
      gp sync-await graphnode
      gp await-port 8020
      sleep 5
      ./watch.sh
  - name: Ethereum Node
    command: ganache-cli -h 0.0.0.0 -m "$MNEMONIC"
  - name: Graph Node
    command: |
      cd /graph-docker
      docker-compose up -d
      gp sync-done graphnode
  - name: Create deploy
    command: |
      gp sync-await graphnode
      gp await-port 8020
      sleep 5
      cd subgraphs/creatify && yarn create-local && cd -
      cd subgraphs/marketplace && yarn create-local && cd -

vscode:
  extensions:
    - dbaeumer.vscode-eslint
    - graphql.vscode-graphql
    - juanblanco.solidity
