---
image:
  file: .gitpod.Dockerfile
tasks:
  - init: |
      npm install
      cd subgraphs/creatify && yarn install && cd ../..
      cd subgraphs/marketplace && yarn install && cd ../..
  - name: Ethereum Node
    command: ganache-cli -h 0.0.0.0 -m "$MNEMONIC"
  - name: Graph Node
    command: |
      cd ..
      git clone https://github.com/graphprotocol/graph-node/
      cd graph-node/docker
      sed -i -e "s/host.docker.internal/172.17.0.1/g" docker-compose.yml
      docker-compose up

vscode:
  extensions:
    - dbaeumer.vscode-eslint
    - graphql.vscode-graphql
    - juanblanco.solidity
