apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: indexer-postgres-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
