apiVersion: v1
kind: PersistentVolume
metadata:
  name: indexer-postgres-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/postgress/indexer/data"
